$(document).ready(function(){
    $(".rectangle").hover(function(){
        $(this).hide();
        $(".about-text").show()
    })
    $(".rectangle").mouseleave(function(){
        $(this).show();
        $(".about-text").hide()
    })
})
